#!/bin/bash

function get {
    case $1 in
        -s|--state) upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -ce 'state: *charging' ;; # 1 if charging
        -p|--percentage) upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk -F ' +|%' '/percentage/{print$3}' ;;
        *) exit 1 ;;
    esac
}

if [[ ! -d /org/freedesktop/UPower/devices/battery_BAT0 ]]; then 
    exit 1
fi

get $1
upower -m | while read; do
    get $1
done
