#!/bin/bash

function get {
    case $1 in
        -s|--state)
            upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state/{print$2}'
            ;;
        -p|--percentage)
            upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk -F ' +|%' '/percentage/{print$3}'
            ;;
        *)
            echo err
            exit 1
            ;;
    esac
}

get $1
upower -m | while read; do
    get $1
done
