#!/bin/bash

hyprctl devices -j | jq -r '.keyboards[3].active_keymap' | sed -e 's/English.*/EN/' -e 's/Persian/FA/'
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    hyprctl devices -j | jq -r '.keyboards[3].active_keymap' | sed -e 's/English.*/EN/' -e 's/Persian/FA/'
done
