#!/bin/bash

function spaces {
    hyprctl workspaces -j | jq --arg active "$1" --argjson urgent "$2" -Mc 'map({
    id: .id | tostring, 
    active: (if .id | tostring == $active then true else false end), 
    urgent: [.id] | inside($urgent)
}) | .=sort_by(.id)'
}

activews=`hyprctl activeworkspace -j | jq '.id'`
urgentwins='[]'
urgentws="$(hyprctl clients -j | jq -Mc --argjson wins "$urgentwins" '[.[] | select([.address] | inside($wins)) | .workspace.id]')"
spaces "$activews" "$urgentws"
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
case "${line%>>*}" in
    "urgent")
        urgentwins="$(echo "$urgentwins" | jq -Mc --arg win "0x${line#*>>}" --arg active $activewin '. += [$win] | unique | map(select(. != $active))')"
        urgentws="$(hyprctl clients -j | jq -Mc --argjson wins "$urgentwins" '[.[] | select([.address] | inside($wins)) | .workspace.id]')"
        ;;
    "workspace")
        activews="${line#*>>}"
        ;;
    "activewindowv2")
        activewin="0x${line#*>>}"
        if [[ `echo $urgentwins | jq 'length'` -gt 0 ]]; then
            urgentwins="`echo $urgentwins | jq --arg active $activewin 'map(select(. != $active))'`"
            urgentws="$(hyprctl clients -j | jq -Mc --argjson wins "$urgentwins" '[.[] | select([.address] | inside($wins)) | .workspace.id]')"
        fi
        ;;
esac

    spaces "$activews" "$urgentws"
done
