#!/bin/bash

function spaces {
    hyprctl workspaces -j | jq --arg active "$1" --arg urgent "$2" -Mc 'map({
    id: .id | tostring, 
    active: (if .id | tostring == $active then true else false end), 
    urgent: (if .id | tostring == $urgent then true else false end)
}) | .=sort_by(.id)'
}

activews=`hyprctl activeworkspace -j | jq -r '.id'`
spaces "$activews"
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
case "${line%>>*}" in
    "urgent")
        urgent_window="0x${line#*>>}"
        urgent_workspace="$(hyprctl clients -j | jq --arg window "$urgent_window" '.[] | select(.address == $window) | .workspace.id')"
    ;;
    "workspace")
        activews="${line#*>>}"
        if [[ "$activews" == "$urgent_workspace" ]]; then
            urgent_workspace=''
        fi
    ;;
    *) echo default
    ;;
esac

    spaces "$activews" "$urgent_workspace"
done
