#!/bin/bash

hyprctl devices -j | jq -r '.keyboards[3].active_keymap'
socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do
    echo $line | awk -F, '/^activelayout/{print$NF}'
done
