#!/bin/bash

function spaces {
    hyprctl workspaces -j | jq --arg urgent "$1" -Mc 'map({id: .id | tostring, urgent: (if .id | tostring == $urgent then "1" else "0" end)}) | .=sort_by(.id)'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    is_urgent="$(echo $line | sed -ne 's/urgent>>//p')"
    if [[ -n $is_urgent ]]; then
        urgent_window="0x$is_urgent"
        urgent_workspace="$(hyprctl clients -j | jq --arg window "$urgent_window" '.[] | select(.address == $window) | .workspace.id')"
        echo is_urgent $is_urgent urgent_window $urgent_window urgent_workspace $urgent_workspace
    fi

    actived_window="$(echo $line | sed -ne 's/activewindowv2>>//p')"
    if [[ -n $actived_window && "0x$actived_window" == $urgent_window ]]; then
        urgent_workspace=''
    fi

    spaces "$urgent_workspace"
done
