#!/bin/bash

status=$(nmcli -get-values wifi general)
essid=$(nmcli connection | awk '/wlp/ { print $1 }')

if [[ "$status" == "disabled" ]]; then
    icon=""
else
    icon=""
fi

if [[ -z $essid ]]; then
    color="#465059"
else
    color="#37a3d9"
fi


if   [[ "$1" == "--color" ]]; then
    echo $color
elif [[ "$1" == "--essid" ]]; then
    echo $essid
elif [[ "$2" == "--icon"  ]]; then
    echo $icon
fi
