#!/usr/bin/env bash

get() {
    status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
    charging=$(echo "$status" | grep -ce 'state: *charging')
    percentage=$(echo "$status" | awk -F ' +|%' '/percentage/{print $3}')

    echo '{"charging": null, "percentage": 0}' | \
        jq -Mc --arg charging "$charging" --arg percentage "$percentage" \
        '.charging= $charging| .percentage = $percentage'
}

upower -e | grep -q battery || exit 1

get
upower -m | while read; do
    get
done
