#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$(file -Lb --mime-type "$file")"

image() {
	thumbnail="$(thumbnailer "$file")"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$thumbnail" < /dev/null > /dev/tty
}

case "$filetype" in
	image/*) image "$file" "$w" "$h" "$x" "$y" ;;
	text/html) lynx -width="$x" -display_charset=utf-8 -dump "$file"  ;;
	troff) man ./ "$file" | col -b ;;
	text/* | */xml) bat -n --wrap never --terminal-width "$x" -f "$file" ;;
	# text/markdown) bat -n --wrap never --terminal-width "$x" -f "$file" ;;
	application/json) bat -n --wrap never --terminal-width "$x" -f "$file" ;;
	text/troff) bat -n --wrap never -l groff --terminal-width "$x" -f "$file" ;;
	application/*zip | application/zstd | application/x-xz | application/x-rar) atool --list "$file" ;;
	audio/* | application/octet-stream) mediainfo "$file" || exit 1;;
	video/* ) image "$file" "$w" "$h" "$x" "$y" ;;
	*/pdf)
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$file")" | sha256sum | awk '{print $file}')"
		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
		image "$CACHE.jpg" "$w" "$h" "$x" "$y"
		;;
	*opendocument*) odt2txt "$file" ;;
	application/pgp-encrypted) gpg -d -- "$file" ;;
esac
exit 1

pistol "$file"
